const DEFAULT={products:[],categories:[],themes:[],settings:{}};
const state={...DEFAULT,cat:"",theme:"",q:"",cart:[]};
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(n)||0);
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const img=(src)=>src||"assets/products/placeholder.svg";
async function read(name,fallback){try{const r=await fetch(`data/${name}.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
async function load(){state.products=await read("products",[]);state.categories=await read("categories",[]);state.themes=await read("themes",[]);state.settings=await read("settings",{siteName:"Techne",eyebrow:"PERSONALIZADOS",heroTitle:"Escolha sua arte.",heroText:"Encontre seu produto, escolha a quantidade e envie o pedido direto pelo WhatsApp.",searchPlaceholder:"Buscar produto, tema ou código...",footerText:"Techne • Produtos personalizados",whatsapp:"",primary:"#ef174d",secondary:"#05a4a9",accent:"#ffb000",showThemes:true,showSearch:true});applySettings();renderFilters();render()}
function applySettings(){const s=state.settings;document.title=`${s.siteName||"Techne"} • Catálogo`;document.documentElement.style.setProperty("--pink",s.primary||"#ef174d");document.documentElement.style.setProperty("--teal",s.secondary||"#05a4a9");document.documentElement.style.setProperty("--yellow",s.accent||"#ffb000");$("#eyebrow").textContent=s.eyebrow||"PERSONALIZADOS";$("#heroTitle").textContent=s.heroTitle||"Escolha sua arte.";$("#heroText").textContent=s.heroText||"";$("#search").placeholder=s.searchPlaceholder||"Buscar produto...";$("#footerText").textContent=s.footerText||s.siteName||"Techne";$("#searchBox").classList.toggle("hidden",s.showSearch===false);$("#themeLine").classList.toggle("hidden",s.showThemes===false)}
function price(p,q){let v=Number(p.price)||0;for(const t of (p.tiers||[]).slice().sort((a,b)=>Number(a.min)-Number(b.min)))if(q>=Number(t.min))v=Number(t.price);return v}
function renderFilters(){const cats=state.categories.filter(x=>x.active);$("#categories").innerHTML=`<button class="${!state.cat?"active":""}" onclick="setCat('')">Todos</button>`+cats.map(x=>`<button class="${state.cat===x.id?"active":""}" onclick="setCat('${esc(x.id)}')">${esc(x.name)}</button>`).join("");const ts=state.themes.filter(x=>x.active);$("#themes").innerHTML=`<option value="">Todos</option>`+ts.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("");$("#themes").value=state.theme}
function setCat(id){state.cat=id;state.theme="";renderFilters();render()}
$("#themes").addEventListener("change",e=>{state.theme=e.target.value;render()});$("#search").addEventListener("input",e=>{state.q=e.target.value.toLowerCase().trim();render()});
function render(){const list=state.products.filter(p=>p.active!==false&&(state.cat===""||p.categoryId===state.cat)&&(state.theme===""||p.themeId===state.theme)&&`${p.name} ${p.code} ${p.description}`.toLowerCase().includes(state.q));$("#empty").classList.toggle("hidden",!!list.length);$("#products").innerHTML=list.map(p=>{const c=state.categories.find(x=>x.id===p.categoryId),t=state.themes.find(x=>x.id===p.themeId);return `<article class="card" onclick="openProduct('${esc(p.id)}')"><div class="photo"><img src="${esc(img(p.image))}" alt="${esc(p.name)}" onerror="this.src='assets/products/placeholder.svg'"><span class="code">${esc(p.code)}</span></div><div class="card-body"><small>${esc(c?.name||"")}${t?" • "+esc(t.name):""}</small><h3>${esc(p.name)}</h3><strong>A partir de ${money(p.price)}</strong><button class="primary" onclick="event.stopPropagation();add('${esc(p.id)}',1)">＋ Adicionar</button></div></article>`}).join("");$("#cartCount").textContent=state.cart.reduce((s,x)=>s+x.qty,0)}
function openProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;$("#productModal").dataset.id=id;$("#productModal").dataset.qty=1;$("#productModal").innerHTML=`<div class="modal"><button class="modal-close" onclick="closeModal('productModal')">✕</button><div class="modal-photo"><img src="${esc(img(p.image))}" onerror="this.src='assets/products/placeholder.svg'"></div><div class="modal-info"><span class="tag">CÓDIGO: ${esc(p.code)}</span><h2>${esc(p.name)}</h2><p>${esc(p.description||"")}</p><div class="pricebox"><span>Preço unitário</span><b id="modalPrice">${money(price(p,1))}</b></div><div class="qty"><button onclick="changeModal(-1)">−</button><b id="modalQty">1</b><button onclick="changeModal(1)">＋</button></div><p>Total: <b id="modalTotal">${money(price(p,1))}</b></p><button class="primary" onclick="addFromModal('${esc(p.id)}')">🛒 Adicionar ao pedido</button></div></div>`;$("#productModal").classList.remove("hidden")}
function changeModal(d){const box=$("#productModal"),q=Math.max(1,Number(box.dataset.qty)+d);box.dataset.qty=q;const p=state.products.find(x=>x.id===box.dataset.id);$("#modalQty").textContent=q;$("#modalPrice").textContent=money(price(p,q));$("#modalTotal").textContent=money(price(p,q)*q)}
function addFromModal(id){add(id,Number($("#productModal").dataset.qty));closeModal("productModal");openCart()}
function add(id,qty){const x=state.cart.find(x=>x.id===id);if(x)x.qty+=qty;else state.cart.push({id,qty});render()}
function updateQty(id,d){const x=state.cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<1)state.cart=state.cart.filter(a=>a.id!==id);renderCart();render()}
function removeItem(id){state.cart=state.cart.filter(x=>x.id!==id);renderCart();render()}
function closeModal(id){$("#"+id).classList.add("hidden")}
function openCart(){renderCart();$("#cartModal").classList.remove("hidden")}
function renderCart(){let total=0;const items=state.cart.map(x=>{const p=state.products.find(a=>a.id===x.id);if(!p)return "";const u=price(p,x.qty),sub=u*x.qty;total+=sub;return `<div class="cart-item"><img src="${esc(img(p.image))}" onerror="this.src='assets/products/placeholder.svg'"><div class="cart-info"><b>${esc(p.name)}</b><small>Código: ${esc(p.code)}</small><div class="mini"><button onclick="updateQty('${esc(p.id)}',-1)">−</button><span>${x.qty}</span><button onclick="updateQty('${esc(p.id)}',1)">＋</button><button onclick="removeItem('${esc(p.id)}')">🗑</button></div><b>${money(sub)}</b></div></div>`}).join("");const msg=[`Olá! Quero fazer um pedido pelo catálogo ${state.settings.siteName||"Techne"}:`,``,...state.cart.map(x=>{const p=state.products.find(a=>a.id===x.id),u=price(p,x.qty);return `• ${p.name} | Código: ${p.code} | Qtd: ${x.qty} | Unit.: ${money(u)} | Subtotal: ${money(u*x.qty)}`}),``,`Total: ${money(total)}`].join("\n");$("#cartModal").innerHTML=`<aside class="cart"><div class="cart-head"><h2>Seu pedido</h2><button onclick="closeModal('cartModal')">✕</button></div><div class="cart-items">${items||'<div class="empty">Carrinho vazio.</div>'}</div>${state.cart.length?`<div class="checkout-form"><input id="customerName" placeholder="Seu nome (opcional)"><textarea id="customerNote" placeholder="Observações (opcional)"></textarea></div>`:""}<div class="cart-total"><span>Total</span><b>${money(total)}</b></div>${state.cart.length?`<button class="wa" onclick="checkoutWhatsApp()">💬 Finalizar pelo WhatsApp</button>`:""}</aside>`}
function checkoutWhatsApp(){const name=$("#customerName")?.value.trim(),note=$("#customerNote")?.value.trim();let total=state.cart.reduce((s,x)=>s+price(state.products.find(p=>p.id===x.id),x.qty)*x.qty,0);const lines=[`Olá! Quero fazer um pedido pelo catálogo ${state.settings.siteName||"Techne"}:`,``,name?`Nome: ${name}`:"",...state.cart.map(x=>{const p=state.products.find(a=>a.id===x.id),u=price(p,x.qty);return `• ${p.name} | Código: ${p.code} | Qtd: ${x.qty} | Unit.: ${money(u)} | Subtotal: ${money(u*x.qty)}`}),note?`\nObservações: ${note}`:"",``,`Total: ${money(total)}`].filter(Boolean);const wa=String(state.settings.whatsapp||"").replace(/\D/g,"");if(!wa){alert("O WhatsApp ainda não foi configurado no painel Admin.");return}window.open(`https://wa.me/${wa}?text=${encodeURIComponent(lines.join("\n"))}`,"_blank")}
$("#cartBtn").onclick=openCart;document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal("productModal");closeModal("cartModal")}});load();
